name: Compile km_morpheuscast_xtreme
on:
  workflow_dispatch:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-core:
    runs-on: ubuntu-latest
    container: chokogroup/chokogroup:ubuntu-18.10-glibc-2.28
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Compile core
        run: |
          make -j$(nproc) platform=sun8i ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: km_morpheuscast_xtreme_libretro
          path: ./*_libretro.so
